build:
	docker build -t postgres_security_separation_of_responsibilities-bl-server .

run:
	docker run --name postgres_security_separation_of_responsibilities-bl-server --rm -d -p 5432:5432 postgres_security_separation_of_responsibilities-bl-server


